channels:
  - conda-forge
dependencies:
  - python >=3.7.1,<3.10
  - pip >=21.3.1
  - gdal >=3.3.3,<3.5.1
  - pandas >=1.3.2,<1.4.3
  - matplotlib >=3.4.2,<3.6.0
  - statista >=0.1.1
  - pip:
      - loguru >=0.5.3
